[pytest]
addopts = --html=reports/report.html --self-contained-html
markers =
    e2e: Marks tests as end-to-end tests that runs through the entire application flow.
    smoke: Marks tests as smoke tests for fast checking.
    sanity: Marks tests as sanity tests for comprehensive 